"""Scheduling leases retries and durable operations"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "4c3b17726280"
down_revision = "5cb4bac13ed5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("attempts", sa.Column("slot", sa.Integer(), server_default="0", nullable=False))
    op.add_column(
        "attempts",
        sa.Column(
            "claim_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
    )
    op.add_column("attempts", sa.Column("fence", sa.Integer(), server_default="1", nullable=False))
    op.add_column(
        "attempts",
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("attempts", sa.Column("outcome", sa.String(length=32), nullable=True))
    op.add_column(
        "attempts", sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("attempts", sa.Column("error", sa.Text(), nullable=True))
    op.drop_index(
        op.f("ix_attempt_active_worker"),
        table_name="attempts",
        postgresql_where="(finished_at IS NULL)",
    )
    op.create_index(
        "ix_attempt_active_slot",
        "attempts",
        ["worker_id", "slot"],
        unique=True,
        postgresql_where=sa.text("finished_at IS NULL"),
    )
    op.create_index(op.f("ix_attempts_expires_at"), "attempts", ["expires_at"], unique=False)
    op.create_unique_constraint("attempts_claim_id_key", "attempts", ["claim_id"])
    op.add_column("jobs", sa.Column("priority", sa.Integer(), server_default="0", nullable=False))
    op.add_column("jobs", sa.Column("timeout", sa.Float(), server_default="15", nullable=False))
    op.add_column(
        "jobs", sa.Column("max_retries", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("jobs", sa.Column("retry_delay", sa.Float(), server_default="1", nullable=False))
    op.add_column(
        "jobs", sa.Column("retry_jitter", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column(
        "jobs", sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("jobs", sa.Column("idempotency_key", sa.String(length=128), nullable=True))
    op.add_column("jobs", sa.Column("request_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "jobs",
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("jobs", sa.Column("depends_on", sa.UUID(), nullable=True))
    op.drop_index(
        op.f("ix_jobs_queue"),
        table_name="jobs",
        postgresql_where="((status)::text = 'QUEUED'::text)",
    )
    op.create_index(
        "ix_jobs_queue",
        "jobs",
        ["priority", "available_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('QUEUED','RETRY_WAIT')"),
    )
    op.create_index("ix_jobs_created", "jobs", ["created_at"], unique=False)
    op.create_index("ix_jobs_status", "jobs", ["status"], unique=False)
    op.create_unique_constraint("jobs_idempotency_key_key", "jobs", ["idempotency_key"])
    op.create_foreign_key("jobs_depends_on_fkey", "jobs", "jobs", ["depends_on"], ["id"])
    op.add_column(
        "workers",
        sa.Column("state", sa.String(length=24), server_default="HEALTHY", nullable=False),
    )
    op.add_column(
        "workers", sa.Column("capacity", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "workers",
        sa.Column(
            "capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='["sleep","calculate_pi","hash_text","flaky"]',
            nullable=False,
        ),
    )
    op.add_column("workers", sa.Column("session_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "workers",
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    op.alter_column("attempts", "claim_id", server_default=None)
    op.execute(
        "UPDATE jobs SET attempt_count = (SELECT count(*) FROM attempts WHERE attempts.job_id = jobs.id)"
    )
    op.execute(
        "UPDATE attempts SET outcome = jobs.status FROM jobs WHERE jobs.id = attempts.job_id AND attempts.finished_at IS NOT NULL"
    )
    op.drop_constraint("jobs_status_check", "jobs", type_="check")
    op.create_check_constraint(
        "jobs_status_check",
        "jobs",
        "status IN ('QUEUED','LEASED','RUNNING','SUCCEEDED','FAILED','CANCELLED','RETRY_WAIT','DEAD_LETTER')",
    )


def downgrade():
    # Refuse lossy downgrades; stop workers and resolve new states first.
    connection = op.get_bind()
    if connection.scalar(
        sa.text("SELECT EXISTS(SELECT 1 FROM jobs WHERE status IN ('RETRY_WAIT','DEAD_LETTER'))")
    ):
        raise RuntimeError("Resolve RETRY_WAIT/DEAD_LETTER jobs before downgrading")
    if connection.scalar(
        sa.text(
            "SELECT EXISTS(SELECT worker_id FROM attempts WHERE finished_at IS NULL GROUP BY worker_id HAVING count(*) > 1)"
        )
    ):
        raise RuntimeError("Drain concurrent worker slots before downgrading")
    op.drop_constraint("jobs_status_check", "jobs", type_="check")
    op.create_check_constraint(
        "jobs_status_check",
        "jobs",
        "status IN ('QUEUED','LEASED','RUNNING','SUCCEEDED','FAILED','CANCELLED')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "registered_at")
    op.drop_column("workers", "session_hash")
    op.drop_column("workers", "capabilities")
    op.drop_column("workers", "capacity")
    op.drop_column("workers", "state")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("jobs_depends_on_fkey", "jobs", type_="foreignkey")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("jobs_idempotency_key_key", "jobs", type_="unique")
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_index("ix_jobs_created", table_name="jobs")
    op.drop_index(
        "ix_jobs_queue",
        table_name="jobs",
        postgresql_where=sa.text("status IN ('QUEUED','RETRY_WAIT')"),
    )
    op.create_index(
        op.f("ix_jobs_queue"),
        "jobs",
        ["created_at", "id"],
        unique=False,
        postgresql_where="((status)::text = 'QUEUED'::text)",
    )
    op.drop_column("jobs", "depends_on")
    op.drop_column("jobs", "available_at")
    op.drop_column("jobs", "metadata_json")
    op.drop_column("jobs", "request_hash")
    op.drop_column("jobs", "idempotency_key")
    op.drop_column("jobs", "attempt_count")
    op.drop_column("jobs", "retry_jitter")
    op.drop_column("jobs", "retry_delay")
    op.drop_column("jobs", "max_retries")
    op.drop_column("jobs", "timeout")
    op.drop_column("jobs", "priority")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("attempts_claim_id_key", "attempts", type_="unique")
    op.drop_index(op.f("ix_attempts_expires_at"), table_name="attempts")
    op.drop_index(
        "ix_attempt_active_slot",
        table_name="attempts",
        postgresql_where=sa.text("finished_at IS NULL"),
    )
    op.create_index(
        op.f("ix_attempt_active_worker"),
        "attempts",
        ["worker_id"],
        unique=True,
        postgresql_where="(finished_at IS NULL)",
    )
    op.drop_column("attempts", "error")
    op.drop_column("attempts", "output")
    op.drop_column("attempts", "outcome")
    op.drop_column("attempts", "expires_at")
    op.drop_column("attempts", "fence")
    op.drop_column("attempts", "claim_id")
    op.drop_column("attempts", "slot")
    op.drop_table("system_events")
    # ### end Alembic commands ###
